(()=>{
const phone=document.getElementById('waChat'),body=phone?.querySelector('.wa-body'),form=document.getElementById('waForm'),input=document.getElementById('waInput');if(!body)return;
const topics=[['Order capture','Nantara collects the customer, products, quantities, and delivery details in one conversation. Missing information is checked before an order reaches your connected system. Requests outside the agreed rules go to your team.'],['Stock & products','Connect your catalogue and inventory source to answer product questions and check availability. When an item is unavailable, the workflow can suggest an approved alternative or ask your team to help.'],['Invoices & payments','Approved orders can generate invoices and payment instructions. Payment status must come from your connected payment system; a customer saying “paid” is not confirmation. Your team handles mismatches and exceptions.'],['Getting started','We map one priority workflow, connect your existing tools, and test sample orders with your team. Typical setup takes 5–7 days, depending on scope and access. We agree on review rules before launch.']];
const scene=[['out','Hi, we need 24 cartons of oat milk for our café. Can you deliver on Friday?'],['in','Welcome to Northline Supply. We have Barista Oat, 12 × 1L per carton. Would you like 24 cartons?'],['out','Yes. Send 18 to our main café and 6 to the new branch.'],['in','I can split the delivery. I have the main café address on file. What is the new branch address?'],['out','18 Garden Street. Both deliveries before noon, please.'],['card','Order ready for review',[['Product','Barista Oat · 12 × 1L'],['Quantity','24 cartons'],['Split delivery','18 main café / 6 new branch'],['Requested slot','Friday, before noon']]],['in','The delivery request is noted. Your account uses bank transfer before dispatch. Shall I prepare the invoice?'],['out','Yes, please.'],['card','Invoice prepared',[['Reference','DEMO-024'],['Payment','Awaiting bank confirmation'],['Next step','Dispatch after payment clears']]],['in','Your order is recorded and the invoice is ready. Our team will confirm the delivery slot before dispatch.']];
let token=0,started=false,visible=false,choices;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function scroll(){window.nantaraTranslate?.();body.scrollTop=body.scrollHeight}function bubble(kind,text){const el=document.createElement('div');el.className='wa-msg wa-'+kind+' live';el.textContent=text;const t=document.createElement('span');t.className='wa-time';t.textContent=new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});el.append(t);body.append(el);scroll();return el}
function contact(el){const a=document.createElement('a');a.href=window.NANTARA_CONFIG.whatsappUrl;a.target='_blank';a.rel='noopener noreferrer';a.className='chat-contact';a.textContent='Talk to our team on WhatsApp';el.append(a)}
function stop(){token++;body.querySelectorAll('.chat-typing').forEach(e=>e.remove());phone.setAttribute('aria-busy','false')}
function options(){choices?.remove();choices=document.createElement('div');choices.className='chat-options';choices.setAttribute('aria-label','Explore Nantara');topics.forEach(t=>{const b=document.createElement('button');b.type='button';b.textContent=t[0];b.onclick=()=>{stop();choices.remove();bubble('out',t[0]);contact(bubble('in',t[1]));options()};choices.append(b)});body.append(choices);scroll()}
async function wait(ms,id){let left=reduced?0:ms;while(left>0){await new Promise(r=>setTimeout(r,100));if(id!==token)return false;if(visible&&!document.hidden)left-=100}return id===token}
async function run(){stop();const id=token;body.replaceChildren();choices=null;phone.setAttribute('aria-busy','true');for(const s of scene){if(!await wait(s[0]==='out'?2100:1000,id))return;if(s[0]!=='out'){const ty=bubble('in','');ty.classList.add('chat-typing');ty.setAttribute('aria-label','Typing');ty.innerHTML='<span></span><span></span><span></span>';if(!await wait(1900,id))return;ty.remove()}if(s[0]==='card'){const el=bubble('in',s[1]);s[2].forEach(([k,v])=>{const row=document.createElement('div');row.className='chat-detail';const label=document.createElement('span'),value=document.createElement('b');label.textContent=k;value.textContent=v;row.append(label,value);el.append(row)});scroll()}else bubble(s[0],s[1]);}phone.setAttribute('aria-busy','false');contact(bubble('in','A structured order, with a review step where it matters. Explore the workflow below.'));options()}
const bar=document.createElement('div');bar.className='chat-demo-bar';const label=document.createElement('span');label.textContent='Northline Supply · Illustrative conversation';bar.append(label);[['Replay',()=>{started=true;run()}],['Explore the workflow',()=>{stop();options()}]].forEach(([text,fn])=>{const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=fn;bar.append(b)});body.before(bar);
form.addEventListener('submit',e=>{e.preventDefault();const text=input.value.trim();if(!text)return;stop();choices?.remove();bubble('out',text);input.value='';contact(bubble('in','For further consultation, reach out to us on WhatsApp.'));options();input.focus()});body.replaceChildren();options();new IntersectionObserver(es=>{visible=es[0].isIntersecting;if(visible&&!started){started=true;run()}},{threshold:.25}).observe(phone);
})();
