(()=>{
 const cfg=window.NANTARA_CONFIG||{},key='nantara-cookie-consent';let consent=null;
 try{consent=localStorage.getItem(key)}catch{}
 let started=false;
 function analytics(){if(started||!/^G-[A-Z0-9]+$/.test(cfg.ga4Id||''))return;started=true;window.dataLayer=window.dataLayer||[];window.gtag=function(){dataLayer.push(arguments)};gtag('js',new Date());gtag('config',cfg.ga4Id);const s=document.createElement('script');s.async=true;s.src='https://www.googletagmanager.com/gtag/js?id='+encodeURIComponent(cfg.ga4Id);document.head.append(s)}
 function banner(){if(document.querySelector('.cookie-panel'))return;const panel=document.createElement('section');panel.className='cookie-panel';panel.setAttribute('aria-label','Cookie preferences');panel.innerHTML='<p>We save your cookie preference on this device. With your permission, optional analytics may help us understand website usage. <a href="Privacy Policy.html">Privacy Policy</a></p><div class="cookie-actions"><button type="button" data-choice="essential">Essential only</button><button type="button" data-choice="analytics">Allow analytics</button></div>';panel.addEventListener('click',e=>{const choice=e.target.dataset.choice;if(!choice)return;consent=choice;try{localStorage.setItem(key,choice)}catch{}panel.remove();if(choice==='analytics')analytics();else if(started)location.reload()});document.body.append(panel)}
 if(consent==='analytics')analytics();if(!consent)banner();
 const footer=document.querySelector('footer')||document.body;const settings=document.createElement('button');settings.type='button';settings.className='cookie-settings';settings.textContent='Cookie preferences';settings.onclick=banner;footer.append(settings);
 const contact=document.createElement('div');contact.className='contact-extra';contact.innerHTML='Contact: <a href="mailto:nantaraai@gmail.com">nantaraai@gmail.com</a>';footer.append(contact);
 const form=document.getElementById('waForm'),input=document.getElementById('waInput'),button=document.getElementById('waSendBtn');
 if(form&&input){input.setAttribute('aria-label','Your message to the Nantara demo');if(button)button.setAttribute('aria-label','Send message');const error=document.createElement('p');error.className='form-feedback';error.id='message-feedback';error.setAttribute('role','status');form.after(error);input.setAttribute('aria-describedby',error.id);form.addEventListener('submit',e=>{if(!input.value.trim()){e.preventDefault();e.stopImmediatePropagation();error.textContent='Please enter a message before sending.';input.setAttribute('aria-invalid','true');input.focus()}else{error.textContent='';input.removeAttribute('aria-invalid')}},true);if(button)new MutationObserver(()=>{form.setAttribute('aria-busy',String(button.disabled));button.setAttribute('aria-label',button.disabled?'Sending message…':'Send message')}).observe(button,{attributes:true,attributeFilter:['disabled']})}
})();
